# Generated by Django 3.2.8 on 2021-11-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(choices=[('-1', '--Select--'), ('IND', 'INDIA'), ('NZ', 'NEW ZEALAND')], default=-1, max_length=50),
        ),
    ]
