# Generated by Django 3.2.8 on 2021-11-09 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_player_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
